# Generated by Django 5.0.6 on 2026-09-05 07:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'finance_expense_category',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_title', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for a chain-wide/head-office account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='branches.branch')),
            ],
            options={
                'db_table': 'finance_bank_account',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counted_closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='branches.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_cash_register',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('DEPOSIT', 'Cash Deposit (branch -> bank)'), ('WITHDRAWAL', 'Withdrawal'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('SALARY_PAYMENT', 'Salary Payment'), ('EXPENSE_PAYMENT', 'Expense Payment'), ('TRANSFER_IN', 'Transfer In (between own accounts)'), ('TRANSFER_OUT', 'Transfer Out (between own accounts)'), ('OTHER_INCOME', 'Other Income')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.bankaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_bank_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bank_account', 'tx_type'], name='finance_ban_bank_ac_7793a6_idx'), models.Index(fields=['branch'], name='finance_ban_branch__97be33_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_from', models.CharField(choices=[('CASH', 'Cash Register'), ('BANK', 'Bank Account')], default='CASH', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.bankaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'db_table': 'finance_expense',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['branch', 'category'], name='finance_exp_branch__51d40f_idx')],
            },
        ),
    ]
