# Generated by Django 5.0.6 on 2026-09-05 07:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'inventory_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'inventory_manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('sku', models.CharField(help_text='Internal SKU / barcode', max_length=64, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('unit_type', models.CharField(choices=[('TABLET', 'Tablet'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CAPSULE', 'Capsule'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('pack_size', models.CharField(blank=True, help_text="e.g. '10 tablets/strip'", max_length=50)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Chain-wide low-stock alert threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_medicine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Purchase In'), ('SALE_OUT', 'Sale Out'), ('RETURN_IN', 'Customer Return In'), ('ADJUSTMENT', 'Adjustment'), ('EXPIRED_WRITE_OFF', 'Expired Write-off'), ('DAMAGED_WRITE_OFF', 'Damaged Write-off'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for in-movements, negative for out-movements')),
                ('reference', models.CharField(blank=True, help_text='Sale/PO/Transfer reference number', max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiry_date', models.DateField(db_index=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='branches.branch')),
            ],
            options={
                'db_table': 'inventory_batch',
                'ordering': ['expiry_date'],
            },
        ),
    ]
